// Generated by CoffeeScript 1.10.0
(function() {
  var chai, expect, sinon;

  chai = require('chai');

  sinon = require('sinon');

  chai.use(require('sinon-chai'));

  expect = chai.expect;

  describe('circle-ci', function() {
    return beforeEach(function() {
      return this.robot = {
        respond: sinon.spy(),
        hear: sinon.spy()
      };
    });
  });

}).call(this);
